text = input()
text = text.replace("З", "Z")
text = text.replace("з", "Z")
text = text.replace("В", "V")
text = text.replace("в", "V")
text = text.replace("О", "O")
text = text.replace("о", "O")
print(text)
input()
